/**
 * Color tokens — GENERATED from Figma's variable export by
 * kb/eng/projects/design-system-tokens/tools/build_colors.py.
 * Do not edit by hand; re-run the generator instead.
 *
 * Two tiers, mirroring the Figma collections:
 *  - `primitives`: raw color scales. Not emitted as CSS vars directly.
 *  - `colors.{dark,light}.content.*`: semantic tokens referencing them,
 *    named exactly as the Figma variables are.
 */
export const primitives = {
  neutral: {
    0: "#FFFFFF",
    25: "#FFF9F5",
    50: "#F9F8F7",
    75: "#F2F1F0",
    100: "#EEEDEC",
    125: "#E8E7E6",
    150: "#E0DEDC",
    200: "#D0CECC",
    250: "#C0BEBC",
    300: "#B5B3B1",
    350: "#A0A09E",
    400: "#9C9896",
    450: "#8F8D8B",
    500: "#6E6C6A",
    550: "#6B6968",
    600: "#4A4C4E",
    650: "#4A4847",
    700: "#3E4244",
    750: "#2F3234",
    800: "#2A2B2C",
    825: "#232526",
    850: "#1F2021",
    875: "#1E1F20",
    900: "#1C1D1E",
    925: "#18191A",
    950: "#141618",
    1000: "#000000",
  },
  orange: {
    300: "#FFB584",
    400: "#FF8A3D",
    500: "#FA5300",
    600: "#C74200",
    700: "#943100",
  },
  green: {
    300: "#7AB87C",
    400: "#4CA05A",
    500: "#1E7D45",
    600: "#166638",
    700: "#0E4E2B",
  },
  red: {
    300: "#FF9999",
    400: "#FF6767",
    500: "#C33636",
    600: "#9B2727",
    700: "#751D1D",
  },
  blue: {
    300: "#86B5F6",
    400: "#4F8BEF",
    500: "#2563EB",
    600: "#1D4EBA",
    700: "#153A8A",
  },
  yellow: {
    300: "#FCCB58",
    400: "#ECAB2E",
    500: "#D97706",
    600: "#B26003",
    700: "#8A4A02",
  },
  purple: {
    300: "#CBA6FF",
    400: "#AB81FB",
    500: "#8B5CF6",
    600: "#6F42C1",
    700: "#532E91",
  },
  pink: {
    300: "#F988B4",
    400: "#EF5793",
    500: "#DB2777",
    600: "#AF1D5E",
    700: "#851547",
  },
  teal: {
    300: "#5EC6B9",
    400: "#32ADA0",
    500: "#0D9488",
    600: "#0A766C",
    700: "#075951",
  },
} as const;

export const colors = {
  common: {
    brand: {
      primary: primitives.orange[500],
      accent: primitives.orange[400],
    },
    semantic: {
      success: primitives.green[500],
      destructive: primitives.red[500],
      info: primitives.blue[500],
      warning: primitives.yellow[500],
    },
  },
  dark: {
    content: {
      bg: {
        accent: primitives.orange[400],
        background: primitives.neutral[925],
        "card-1": primitives.neutral[875],
        "card-2": primitives.neutral[825],
        "card-elevated": primitives.neutral[750],
        failure: primitives.red[500],
        info: primitives.blue[500],
        muted: primitives.neutral[850],
        popover: primitives.neutral[950],
        primary: primitives.orange[500],
        secondary: primitives.neutral[900],
        selected: `color-mix(in srgb, ${primitives.orange[500]} 30%, transparent)`,
        success: primitives.green[500],
        warning: primitives.yellow[500],
      },
      border: {
        active: primitives.orange[500],
        default: primitives.neutral[750],
        disabled: primitives.neutral[875],
        error: primitives.red[400],
        focus: primitives.neutral[500],
        hover: primitives.neutral[600],
        input: primitives.neutral[750],
        "input-focus": primitives.neutral[500],
        "input-hover": primitives.neutral[600],
        strong: primitives.neutral[700],
        subtle: primitives.neutral[875],
        success: primitives.green[300],
        warning: primitives.yellow[300],
      },
      code: {
        bg: primitives.neutral[950],
        border: primitives.neutral[750],
        text: primitives.orange[400],
      },
      focus: {
        ring: `color-mix(in srgb, ${primitives.orange[500]} 50%, transparent)`,
      },
      icon: {
        brand: primitives.orange[500],
        dark: primitives.neutral[925],
        decorative: primitives.orange[400],
        default: primitives.neutral[450],
        disabled: primitives.neutral[550],
        emphasis: primitives.neutral[0],
        failure: primitives.red[400],
        info: primitives.blue[300],
        muted: primitives.neutral[550],
        subtle: primitives.neutral[500],
        success: primitives.green[300],
        warning: primitives.yellow[300],
      },
      interactive: {
        "danger-default": primitives.red[500],
        "danger-hover": primitives.red[600],
        "danger-pressed": primitives.red[700],
        "primary-default": primitives.orange[500],
        "primary-hover": primitives.orange[600],
        "primary-pressed": primitives.orange[700],
        "secondary-default": primitives.neutral[825],
        "secondary-hover": primitives.neutral[800],
        "secondary-pressed": primitives.neutral[875],
        "success-default": primitives.green[500],
        "success-hover": primitives.green[600],
        "success-pressed": primitives.green[700],
      },
      link: {
        default: primitives.blue[300],
        hover: primitives.blue[400],
        visited: primitives.purple[400],
      },
      overlay: {
        default: `color-mix(in srgb, ${primitives.neutral[1000]} 60%, transparent)`,
        heavy: `color-mix(in srgb, ${primitives.neutral[1000]} 80%, transparent)`,
        light: `color-mix(in srgb, ${primitives.neutral[1000]} 40%, transparent)`,
      },
      palette: {
        "1-brand": primitives.orange[500],
        "2-blue": primitives.blue[500],
        "3-green": primitives.green[500],
        "4-violet": "#7C3AED",
        "5-pink": primitives.pink[500],
        "6-amber": "#B45309",
        "7-teal": "#0F766E",
        "8-purple": primitives.purple[600],
        "9-indigo": "#4F46E5",
        "10-red": primitives.red[500],
        "11-gold": primitives.yellow[600],
        "12-sage": primitives.green[600],
        "13-sky": "#0284C7",
        "14-lime": "#4D7C0F",
        "15-magenta": "#A21CAF",
        "16-slate": "#475569",
        "17-rose": "#E11D48",
        "18-mint": "#059669",
      },
      scrollbar: {
        thumb: primitives.neutral[700],
        "thumb-hover": primitives.neutral[600],
        track: primitives.neutral[925],
      },
      selection: {
        bg: `color-mix(in srgb, ${primitives.orange[500]} 30%, transparent)`,
        text: primitives.neutral[0],
      },
      skeleton: {
        base: primitives.neutral[825],
        shimmer: primitives.neutral[750],
      },
      status: {
        "approved-bg": primitives.green[500],
        "approved-text": primitives.green[300],
        "draft-bg": primitives.neutral[550],
        "draft-text": primitives.neutral[450],
        "failed-bg": primitives.red[500],
        "failed-text": primitives.red[400],
        "progress-bg": primitives.purple[500],
        "progress-text": primitives.purple[300],
        "review-bg": primitives.orange[500],
        "review-text": primitives.orange[400],
      },
      text: {
        accent: primitives.orange[400],
        decorative: primitives.orange[400],
        failure: primitives.red[400],
        foreground: primitives.neutral[25],
        info: primitives.blue[300],
        muted: primitives.neutral[400],
        placeholder: primitives.neutral[550],
        primary: primitives.neutral[0],
        secondary: primitives.neutral[450],
        success: primitives.green[300],
        tertiary: primitives.neutral[500],
        warning: primitives.yellow[300],
      },
      tooltip: {
        bg: primitives.neutral[800],
        text: primitives.neutral[25],
      },
    },
  },
  light: {
    content: {
      bg: {
        accent: primitives.orange[400],
        background: primitives.neutral[50],
        "card-1": primitives.neutral[0],
        "card-2": primitives.neutral[75],
        "card-elevated": primitives.neutral[0],
        failure: primitives.red[500],
        info: primitives.blue[500],
        muted: primitives.neutral[100],
        popover: primitives.neutral[0],
        primary: primitives.orange[500],
        secondary: primitives.neutral[125],
        selected: `color-mix(in srgb, ${primitives.orange[500]} 30%, transparent)`,
        success: primitives.green[500],
        warning: primitives.yellow[500],
      },
      border: {
        active: primitives.orange[500],
        default: primitives.neutral[150],
        disabled: primitives.neutral[100],
        error: primitives.red[500],
        focus: primitives.neutral[350],
        hover: primitives.neutral[250],
        input: primitives.neutral[200],
        "input-focus": primitives.neutral[350],
        "input-hover": primitives.neutral[250],
        strong: primitives.neutral[200],
        subtle: primitives.neutral[100],
        success: primitives.green[500],
        warning: primitives.yellow[500],
      },
      code: {
        bg: primitives.neutral[75],
        border: primitives.neutral[150],
        text: primitives.orange[700],
      },
      focus: {
        ring: `color-mix(in srgb, ${primitives.orange[500]} 50%, transparent)`,
      },
      icon: {
        brand: primitives.orange[500],
        dark: primitives.neutral[925],
        decorative: primitives.orange[500],
        default: primitives.neutral[550],
        disabled: primitives.neutral[300],
        emphasis: primitives.neutral[925],
        failure: primitives.red[500],
        info: primitives.blue[500],
        muted: primitives.neutral[300],
        subtle: primitives.neutral[450],
        success: primitives.green[500],
        warning: primitives.yellow[500],
      },
      interactive: {
        "danger-default": primitives.red[500],
        "danger-hover": primitives.red[600],
        "danger-pressed": primitives.red[700],
        "primary-default": primitives.orange[500],
        "primary-hover": primitives.orange[600],
        "primary-pressed": primitives.orange[700],
        "secondary-default": primitives.neutral[100],
        "secondary-hover": primitives.neutral[150],
        "secondary-pressed": primitives.neutral[200],
        "success-default": primitives.green[500],
        "success-hover": primitives.green[600],
        "success-pressed": primitives.green[700],
      },
      link: {
        default: primitives.blue[500],
        hover: primitives.blue[600],
        visited: primitives.purple[600],
      },
      overlay: {
        default: `color-mix(in srgb, ${primitives.neutral[1000]} 50%, transparent)`,
        heavy: `color-mix(in srgb, ${primitives.neutral[1000]} 70%, transparent)`,
        light: `color-mix(in srgb, ${primitives.neutral[1000]} 30%, transparent)`,
      },
      palette: {
        "1-brand": primitives.orange[500],
        "2-blue": primitives.blue[500],
        "3-green": primitives.green[500],
        "4-violet": primitives.purple[500],
        "5-pink": primitives.pink[500],
        "6-amber": primitives.yellow[500],
        "7-teal": primitives.teal[500],
        "8-purple": primitives.purple[600],
        "9-indigo": "#818CF8",
        "10-red": primitives.red[500],
        "11-gold": "#E8A33D",
        "12-sage": "#5FA97A",
        "13-sky": "#38BDF8",
        "14-lime": "#65A30D",
        "15-magenta": "#C026D3",
        "16-slate": "#64748B",
        "17-rose": "#F43F5E",
        "18-mint": "#34D399",
      },
      scrollbar: {
        thumb: primitives.neutral[200],
        "thumb-hover": primitives.neutral[250],
        track: primitives.neutral[75],
      },
      selection: {
        bg: `color-mix(in srgb, ${primitives.orange[500]} 20%, transparent)`,
        text: primitives.neutral[1000],
      },
      skeleton: {
        base: primitives.neutral[100],
        shimmer: primitives.neutral[150],
      },
      status: {
        "approved-bg": primitives.green[500],
        "approved-text": primitives.green[600],
        "draft-bg": primitives.neutral[550],
        "draft-text": primitives.neutral[600],
        "failed-bg": primitives.red[500],
        "failed-text": primitives.red[600],
        "progress-bg": primitives.purple[500],
        "progress-text": primitives.purple[600],
        "review-bg": primitives.orange[500],
        "review-text": primitives.orange[600],
      },
      text: {
        accent: primitives.orange[500],
        decorative: primitives.orange[500],
        failure: primitives.red[600],
        foreground: primitives.neutral[1000],
        info: primitives.blue[600],
        muted: primitives.neutral[450],
        placeholder: primitives.neutral[300],
        primary: primitives.neutral[925],
        secondary: primitives.neutral[650],
        success: primitives.green[600],
        tertiary: primitives.neutral[550],
        warning: primitives.yellow[700],
      },
      tooltip: {
        bg: primitives.neutral[925],
        text: primitives.neutral[25],
      },
    },
  },
};
