/**
 * Regenerate `src/v2/index.ts` from the files on disk.
 *
 * The barrel is generated rather than hand-maintained so a component added by
 * `port-lovable-ui.ts` can never be silently unexported — the parity check
 * reads this barrel to decide whether the design system covers the Lovable
 * inventory.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const UI_DIR = resolve("src/v2/components/ui");
const HOOKS_DIR = resolve("src/v2/hooks");
const PATTERNS_DIR = resolve("src/v2/components/patterns");
const CHROME_DIR = resolve("src/v2/components/chrome");

const modules = (dir: string) =>
  readdirSync(dir)
    .filter((f) => /\.tsx?$/.test(f) && !/\.(spec|test|stories)\./.test(f))
    .map((f) => f.replace(/\.tsx?$/, ""))
    .sort();

/**
 * Modules whose flat-barrel exports collide, and how the collision is
 * resolved. Subpath imports are unaffected — `@voxel51/voodo/v2/sonner` still
 * exports `Toaster` under its own name, so a page ported from Lovable keeps
 * working unchanged. Only the convenience barrel needs unique names.
 */
const ALIASES: Record<string, Record<string, string>> = {
  // shadcn ships two toast systems. `toaster` hosts the radix one and keeps
  // the plain names; sonner's host and imperative API are prefixed.
  sonner: { Toaster: "SonnerToaster", toast: "sonnerToast" },
  // `FormField` is react-hook-form's controller wrapper (form.tsx). The
  // labeled row in form-section.tsx is a different thing with the same name.
  "form-section": { FormField: "FormSectionField" },
};

/** Modules excluded from the barrel because another module re-exports them. */
const BARREL_SKIP = new Set(["use-toast"]);

const namedExports = (dir: string, mod: string): string[] => {
  const file = [".tsx", ".ts"]
    .map((ext) => resolve(dir, `${mod}${ext}`))
    .find(existsSync);
  if (!file) return [];
  const code = readFileSync(file, "utf8");
  const names = new Set<string>();
  for (const m of code.matchAll(
    /export\s+(?:declare\s+)?(?:const|function|class|type|interface)\s+([A-Za-z0-9_]+)/g,
  ))
    names.add(m[1]);
  for (const m of code.matchAll(/export\s*\{([^}]*)\}/g))
    for (const part of m[1].split(","))
      if (part.trim()) names.add(part.trim().split(/\s+as\s+/).pop()!.trim());
  return [...names];
};

const ui = modules(UI_DIR);
const hooks = modules(HOOKS_DIR).filter((m) => !BARREL_SKIP.has(m));

/** Pattern groups — one directory per group, each with its own barrel. */
const patterns = existsSync(PATTERNS_DIR)
  ? readdirSync(PATTERNS_DIR, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort()
  : [];

/** Emit `export *`, or an explicit list when the module has aliased names. */
const exportLine = (dir: string, path: string, mod: string): string => {
  const alias = ALIASES[mod];
  if (!alias) return `export * from "${path}";`;
  const names = namedExports(dir, mod);
  const clauses = names.map((n) => (alias[n] ? `${n} as ${alias[n]}` : n));
  return `export { ${clauses.join(", ")} } from "${path}";`;
};

const header = `/**
 * VOODO 2.0 — public API.
 *
 * GENERATED by utils/generate-v2-index.ts. Do not edit by hand.
 *
 * Every module is also reachable at its own subpath, mirroring the Lovable
 * master project's layout, so a ported page can keep its import shape:
 *
 *     import { Button } from "@voxel51/voodo/v2/button";
 *
 * ${ui.length} components, ${patterns.length} pattern group(s), ${hooks.length} hook(s).
 */
`;

const body = [
  ...ui.map((m) => exportLine(UI_DIR, `./components/ui/${m}`, m)),
  "",
  ...(existsSync(CHROME_DIR) ? ['export * from "./components/chrome";'] : []),
  "",
  ...patterns.map((p) => `export * from "./components/patterns/${p}";`),
  "",
  ...hooks.map((m) => exportLine(HOOKS_DIR, `./hooks/${m}`, m)),
  "",
  `export { cn } from "./lib/utils";`,
  `export * from "./lib/vizPalette";`,
  `export * from "./lib/saveStatusStore";`,
].join("\n");

writeFileSync(resolve("src/v2/index.ts"), `${header}\n${body}\n`);
console.log(`Generated src/v2/index.ts (${ui.length} ui modules, ${hooks.length} hooks)`);
