import * as fs from "fs";
import {
  ALL_COLORS,
  BorderColor,
  bgColorClass,
  borderColorClass,
  textColorClass,
} from "../src/types/color";
import { ElementState } from "../src/types/element";

const allColors = [...ALL_COLORS];

const allBorderColors = Object.values(BorderColor);

// Only safelist the element-states actually used with color helpers in the
// components. Open / Dragging / AutoFocus are never paired with a color (e.g.
// Dragging is only used with shadowStyles), so generating ~3 states × every
// color × bg/text/border was pure bloat. If a component starts using one of
// these with a color helper, add it back here and regenerate.
const colorStates = [
  ElementState.Hover,
  ElementState.Focus,
  ElementState.Active,
  ElementState.Selected,
  ElementState.Checked,
  ElementState.Disabled,
];

/**
 * Generate the exact set of color classes the components build dynamically
 * (which Tailwind can't see statically). Base classes come straight from the
 * color maps via the helpers — no guessed prefixes — plus one entry per used
 * element-state.
 * @returns an array of all needed color classes
 */
function generateClasses(): Array<string> {
  const classes = new Set<string>();

  allColors.forEach((color) => {
    classes.add(bgColorClass(color)); // exact base (from map)
    classes.add(textColorClass(color));
    colorStates.forEach((state) => {
      classes.add(bgColorClass(color, state));
      classes.add(textColorClass(color, state));
    });
  });

  allBorderColors.forEach((color) => {
    classes.add(borderColorClass(color));
    colorStates.forEach((state) => {
      classes.add(borderColorClass(color, state));
    });
  });

  return Array.from(classes).sort();
}

const classes = generateClasses();

// Generate TypeScript file
const tsContent = `// Auto-generated - DO NOT EDIT MANUALLY
// Generated by: npm run generate-tailwind-theme
// This file ensures Tailwind scans all possible color class permutations
/**
 * All possible color class combinations including:
 * - Background colors with all element states
 * - Text colors with all element states
 * - Border colors with all element states
 */
// Total classes: ${classes.length}
export const GENERATED_COLOR_CLASSES = [
${classes.map((c) => `  '${c}',`).join("\n")}
] as const;
export default GENERATED_COLOR_CLASSES;
`;

const outFile = "src/styles/color-classes.ts";
fs.writeFileSync(outFile, tsContent);

console.log(`✅ Generated ${classes.length} color class permutations`);
console.log(`📁 Output: ${outFile}`);
