import { writeFileSync } from "fs";
import { ZIndex, Z_INDEX_VALUES } from "../src/types/zIndex";
import { default as tokens } from "../src/theme/tokens";

/**
 * Generate a list of CSS variables from a (maybe) nested object.
 *
 * This method will traverse an object and create a variable of the form
 * `${prefix}-${key}: ${value}`
 * for each leaf node in the object.
 *
 * @param config Configuration object
 * @param prefix Prefix to prepend to the CSS variable
 */
const mapNestedAttributes = (
  config: Record<string, any>,
  prefix?: string
): string[] => {
  const result: string[] = [];

  Object.entries(config).forEach(([key, value]) => {
    if (typeof value === "object") {
      result.push(...mapNestedAttributes(value, `${prefix}-${key}`));
    } else if (typeof value === "string") {
      if (prefix) {
        result.push(`${prefix}-${key}: ${value};`);
      } else {
        result.push(`${key}: ${value};`);
      }
    } else {
      throw new Error(
        `Unsupported value type ${typeof value} for key ${prefix}-${key}`
      );
    }
  });

  return result;
};

const tailwindTheme = `/** AUTO-GENERATED by utils/generate-tailwind-theme.ts **/
@theme static {
  /* Colors */
  ${mapNestedAttributes(tokens.colors.light, "--color").join("\n  ")}
  ${mapNestedAttributes(tokens.colors.common, "--color").join("\n  ")}
  
  /* Spacing */
  --spacing: 0.25rem;
  ${Object.entries(tokens.spacing)
    .map(([key, value]) => `--spacing-${key}: ${value};`)
    .join("\n  ")}

  /* Z-Index */
  ${(Object.entries(Z_INDEX_VALUES) as [ZIndex, number | "auto"][])
    .map(([level, value]) => `--z-${level}: ${value};`)
    .join("\n  ")}

  /* Typography */
  ${Object.entries(tokens.typography.fontFamily)
    .map(
      ([key, value]) =>
        `--font-${key}: ${value.map((v) => (v.includes(" ") ? `"${v}"` : v)).join(", ")};`
    )
    .join("\n  ")}
  ${Object.entries(tokens.typography.fontSize)
    .map(([key, value]) => `--text-${key}: ${value};`)
    .join("\n  ")}

  /* Typography — line-height (Figma's scale; previously never emitted) */
  ${Object.entries(tokens.typography.lineHeight)
    .map(([key, value]) => `--leading-${key}: ${value};`)
    .join("\n  ")}

  /* Typography — weight */
  ${Object.entries(tokens.typography.fontWeight)
    .map(([key, value]) => `--font-weight-${key}: ${value};`)
    .join("\n  ")}

  /* Typography — roles. The names designers apply, from Figma's text styles. */
  ${Object.entries(tokens.typography.role)
    .map(([key, spec]) => `--text-${key}: ${spec.size};`)
    .join("\n  ")}
  ${Object.entries(tokens.typography.role)
    .map(([key, spec]) => `--font-weight-${key}: ${spec.weight};`)
    .join("\n  ")}

  /* Transitions — duration */
  ${Object.entries(tokens.transitions.duration)
    .map(([key, value]) => `--transition-duration-${key}: ${value};`)
    .join("\n  ")}

  /* Transitions — easing */
  ${Object.entries(tokens.transitions.easing)
    .map(([key, value]) => `--transition-easing-${key}: ${value};`)
    .join("\n  ")}

  /* Transitions — presets */
  ${Object.entries(tokens.transitions.preset)
    .map(([key, value]) => `--transition-preset-${key}: ${value};`)
    .join("\n  ")}
}

/* dark theme */
@custom-variant dark (&:where(.dark, .dark *));

.dark {
  ${mapNestedAttributes(tokens.colors.dark, "--color").join("\n  ")}
}
`;

// todo the rest of our styling

writeFileSync("./src/styles/tailwind.css", tailwindTheme);
