import { writeFileSync } from "fs";
import { default as tokens } from "../src/theme/tokens";
import { Z_INDEX_VALUES } from "../src/types/zIndex";

/**
 * Generate `src/theme/cssVar.ts` — a typed, ergonomic accessor that returns
 * `var(--…)` references for every semantic Voodo token, in every family.
 *
 * These are the stable, theme-reactive interop surface for consuming Voodo
 * outside Voodo (e.g. MUI `sx`, emotion, plain CSS-in-JS). Bind to these names
 * rather than hardcoding values or importing raw hex (which would not react to
 * light/dark and could drift). Generated from the same token source as the CSS
 * variables, so the two cannot diverge.
 */

type Nested = { [k: string]: string | Nested };

const walk = (obj: Record<string, unknown>, prefix: string): Nested => {
  const out: Nested = {};
  for (const [key, value] of Object.entries(obj)) {
    if (value && typeof value === "object") {
      out[key] = walk(value as Record<string, unknown>, `${prefix}-${key}`);
    } else {
      out[key] = `var(${prefix}-${key})`;
    }
  }
  return out;
};

const flat = (obj: Record<string, unknown>, prefix: string): Nested => {
  const out: Nested = {};
  for (const key of Object.keys(obj)) out[key] = `var(${prefix}-${key})`;
  return out;
};

const color = {
  brand: walk(tokens.colors.common.brand, "--color-brand"),
  semantic: walk(tokens.colors.common.semantic, "--color-semantic"),
  // bg / text / border / status / icon / overlay / link / palette / skeleton /
  // tooltip / code / scrollbar / selection (mode-reactive at runtime)
  ...walk(tokens.colors.dark.content, "--color-content"),
  action: walk(tokens.colors.dark.action, "--color-action"),
};

const cssVar = {
  color,
  spacing: flat(tokens.spacing, "--spacing"),
  text: flat(tokens.typography.fontSize, "--text"),
  fontFamily: flat(tokens.typography.fontFamily, "--font"),
  z: Object.fromEntries(
    Object.keys(Z_INDEX_VALUES).map((k) => [k, `var(--z-${k})`])
  ),
  transition: {
    duration: flat(tokens.transitions.duration, "--transition-duration"),
    easing: flat(tokens.transitions.easing, "--transition-easing"),
    preset: flat(tokens.transitions.preset, "--transition-preset"),
  },
};

const banner =
  "/** AUTO-GENERATED by utils/generate-css-vars.ts — do not edit by hand. **/\n" +
  "/**\n" +
  " * Typed `var(--…)` references for every semantic Voodo token. The stable,\n" +
  " * theme-reactive surface for consuming Voodo outside Voodo (MUI/emotion/CSS).\n" +
  " * Bind to these instead of hardcoding values; they react to light/dark and\n" +
  " * track token renames. Requires Voodo's CSS (`@voxel51/voodo/theme.css`).\n" +
  " */\n";

writeFileSync(
  "./src/theme/cssVar.ts",
  `${banner}export const cssVar = ${JSON.stringify(cssVar, null, 2)} as const;\n`
);
