import * as fs from "fs";
import {
  ActionColor,
  BackgroundColor,
  bgColorClass,
  BorderColor,
  borderColorClass,
  BrandColor,
  IconColor,
  SemanticColor,
  StatusColor,
  TextColor,
  textColorClass,
} from "../src/types/color";
import { ElementState } from "../src/types/element";

// TODO - can we make this more robust/dynamic? What happens if we add new color types?
const allColors = [
  ...Object.values(ActionColor),
  ...Object.values(BackgroundColor),
  ...Object.values(BrandColor),
  ...Object.values(IconColor),
  ...Object.values(SemanticColor),
  ...Object.values(StatusColor),
  ...Object.values(TextColor),
];

const allBorderColors = Object.values(BorderColor);
const allStates = Object.values(ElementState).filter(
  (s) => s !== ElementState.None
);

/**
 * We need to generate all permutations of classes for:
 * States and Background/Borders/Text colors
 * @returns an array of all possible color classes
 */
function generateClasses(): Array<string> {
  const classes = new Set<string>();

  // Background colors
  allColors.forEach((color) => {
    // Base states
    classes.add(`bg-${color}`);
    classes.add(`bg-content-${color}`); // Add content- prefix version too

    // handle variable syntax
    allStates.forEach((state) => {
      classes.add(bgColorClass(color, state));
    });
  });

  // Text colors
  allColors.forEach((color) => {
    // Base state
    classes.add(`text-${color}`);
    classes.add(`text-content-${color}`);

    // handle variable syntax
    allStates.forEach((state) => {
      classes.add(textColorClass(color, state));
    });
  });

  // Border colors
  allBorderColors.forEach((color) => {
    // Base state
    classes.add(`border-content-${color}`);

    // handle variable syntax
    allStates.forEach((state) => {
      classes.add(borderColorClass(color, state));
    });
  });

  return Array.from(classes).sort();
}

const classes = generateClasses();

// Generate TypeScript file
const tsContent = `// Auto-generated - DO NOT EDIT MANUALLY
// Generated by: npm run generate:colors
// This file ensures Tailwind scans all possible color class permutations
/**
 * All possible color class combinations including:
 * - Background colors with all element states
 * - Text colors with all element states
 * - Border colors with all element states
 */
// Total classes: ${classes.length}
export const GENERATED_COLOR_CLASSES = [
${classes.map((c) => `  '${c}',`).join("\n")}
] as const;
export default GENERATED_COLOR_CLASSES;
`;

const outFile = "src/styles/color-classes.ts";
fs.writeFileSync(outFile, tsContent);

console.log(`✅ Generated ${classes.length} color class permutations`);
console.log(`📁 Output: ${outFile}`);
