import { writeFileSync } from "fs";

import { primitives } from "../src/theme/tokens/colors";
import { default as tokens } from "../src/theme/tokens";

/**
 * Generate `src/theme/tokens.json` — the machine-readable mirror of the token
 * tree, for consumers that cannot import TypeScript.
 *
 * The design system's other generators all emit artifacts for JS/CSS consumers.
 * This one exists for everything else: the FiftyOne Python package syncs
 * `DEFAULT_APP_COLOR_POOL` from it, and any future non-JS consumer (docs
 * tooling, notebooks, plugin SDKs) should read this rather than re-typing hex
 * values or parsing `tokens/colors.ts`.
 *
 * Copied to `dist/tokens.json` on build and exposed as the
 * `@voxel51/voodo/tokens.json` subpath export, so downstream repos can read it
 * straight out of node_modules at the version they have installed.
 */

const banner = {
  $comment:
    "AUTO-GENERATED by utils/generate-tokens-json.ts — do not edit by hand. " +
    "Run `npm run generate-tailwind-theme` in @voxel51/voodo to regenerate.",
};

/**
 * `primitives` is included alongside the semantic tokens even though it is not
 * emitted as CSS variables: non-JS consumers need it to resolve a semantic
 * value back to the scale step it came from (e.g. labeling `#6F42C1` as
 * `purple 600`), which the semantic tree alone cannot express.
 */
writeFileSync(
  "./src/theme/tokens.json",
  `${JSON.stringify({ ...banner, primitives, ...tokens }, null, 2)}\n`
);
