import { default as tokens } from "../src/theme/tokens";
import { writeFileSync } from "fs";

// we'll need to decide whether we want to do `@theme static` to make all variables available to consumers.
// as it stands (`@theme`, no static),
//  tailwind will optimize away anything that's not actually used by a component in this library.
const tailwindTheme = `/** AUTO-GENERATED by utils/generate-tailwind-theme.ts **/
@theme {
  /* Colors */
  --color-primary: ${tokens.colors.dark.primary.main};
  --color-secondary: ${tokens.colors.dark.secondary.main};
  
  /* Spacing */
  ${Object.entries(tokens.spacing)
    .map(([key, value]) => `--spacing-${key}: ${value};`)
    .join("\n  ")}
  
  /* Typography */
  ${Object.entries(tokens.typography.fontFamily)
    .map(
      ([key, value]) =>
        `--font-${key}: ${value.map((v) => (v.includes(" ") ? `"${v}"` : v)).join(", ")};`
    )
    .join("\n  ")}
  ${Object.entries(tokens.typography.fontSize)
    .map(([key, value]) => `--font-size-${key}: ${value};`)
    .join("\n  ")}
}
`;

// todo light/dark
// todo the rest of our styling

writeFileSync("./src/styles/tailwind.css", tailwindTheme);
