name: test and publish package

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use
        type: string
        required: true
      registry-url:
        description: Package registry URL
        type: string
        required: true

    secrets:
      REGISTRY_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}

      - name: Clean install
        run: npm ci

      - name: Test package
        run: npm run test


  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}

      - name: Clean install
        run: npm ci

      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
