name: test and publish package

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use
        type: string
        required: true
      registry-url:
        description: Package registry URL
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/_run_tests.yaml
    with:
      node-version: ${{ inputs.node-version }}
    permissions:
      contents: read

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}

      - name: Clean install
        run: npm ci

      - name: Publish package
        run: npm publish --provenance --access public
