on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  run_tests:
    name: run unit tests
    uses: ./.github/workflows/_run_tests.yaml
    with:
      node-version: 22.22.0
